[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npm run build"

[phases.setup]
nixPkgs = ["nodejs_22"]
nixpkgsArchive = "ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10